// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: db-queries.sql

package sql

import (
	"context"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO common.users(user_name, email, phone, pass, role) 
VALUES($1, $2, $3, $4, $5)
`

type CreateUserParams struct {
	UserName string `db:"user_name" json:"user_name"`
	Email    string `db:"email" json:"email"`
	Phone    string `db:"phone" json:"phone"`
	Pass     string `db:"pass" json:"pass"`
	Role     string `db:"role" json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.UserName,
		arg.Email,
		arg.Phone,
		arg.Pass,
		arg.Role,
	)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT user_id, user_name, email, phone, pass, pss_valid, otp, otp_valid, otp_exp, role 
FROM common.users 
WHERE email = $1
`

// --------------------- AUTHENTICATION ------------------------------
func (q *Queries) GetUserByEmail(ctx context.Context, email string) (CommonUser, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i CommonUser
	err := row.Scan(
		&i.UserID,
		&i.UserName,
		&i.Email,
		&i.Phone,
		&i.Pass,
		&i.PssValid,
		&i.Otp,
		&i.OtpValid,
		&i.OtpExp,
		&i.Role,
	)
	return i, err
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE common.users 
SET pass = $1, pss_valid = $2 
WHERE email = $3
`

type UpdatePasswordParams struct {
	Pass     string `db:"pass" json:"pass"`
	PssValid bool   `db:"pss_valid" json:"pss_valid"`
	Email    string `db:"email" json:"email"`
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.Exec(ctx, updatePassword, arg.Pass, arg.PssValid, arg.Email)
	return err
}
