// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sql

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) error
	GetAllUsers(ctx context.Context) ([]GetAllUsersRow, error)
	// --------------------- AUTHENTICATION ------------------------------
	GetUserByEmail(ctx context.Context, email string) (CommonUser, error)
	GetUserByLogin(ctx context.Context, userName string) (CommonUser, error)
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error
}

var _ Querier = (*Queries)(nil)
