// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Sumon Sarker",
            "email": "suman@satcombd.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/active-flag-change-module": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "active-flag-change-module",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Menu \u0026 Module Load Service"
                ],
                "summary": "active-flag-change-module",
                "parameters": [
                    {
                        "description": "Body data",
                        "name": "Data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ModuleAccessFlag_dto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseDto"
                        }
                    }
                }
            }
        },
        "/assign-branch-year": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "assign-branch-year",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Branch \u0026 Financial Year Service"
                ],
                "summary": "assign-branch-year",
                "parameters": [
                    {
                        "description": "Body data",
                        "name": "Data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.BranchYearSubmit_dto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseDto"
                        }
                    }
                }
            }
        },
        "/branch-select": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "branch-select",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Access Service"
                ],
                "summary": "branch-select",
                "parameters": [
                    {
                        "description": "Body data",
                        "name": "Data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.BranchSelect_dto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseDto"
                        }
                    }
                }
            }
        },
        "/branch-year-load": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "branch-year-load",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Branch \u0026 Financial Year Service"
                ],
                "summary": "branch-year-load",
                "parameters": [
                    {
                        "description": "Body data",
                        "name": "Data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ID_Swag_dto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseDto"
                        }
                    }
                }
            }
        },
        "/comp-year": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "comp-year",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Comp Year Service"
                ],
                "summary": "comp-year",
                "parameters": [
                    {
                        "description": "Body data",
                        "name": "Data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.Comp_year_token_input_dto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseDto"
                        }
                    }
                }
            }
        },
        "/confirm-otp/{id}": {
            "patch": {
                "description": "ConfirmOTPService",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OTP Service"
                ],
                "summary": "ConfirmOTPService",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Body data",
                        "name": "Data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.Confirm_Swag_dto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseDto"
                        }
                    }
                }
            }
        },
        "/dashboard-load/": {
            "get": {
                "description": "test2",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json",
                    "application/json"
                ],
                "tags": [
                    "Menu \u0026 Module Load Service"
                ],
                "summary": "test2",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseDto"
                        }
                    }
                }
            }
        },
        "/dashboard-load/{uuid}": {
            "get": {
                "description": "test",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "DashBoard Load Service"
                ],
                "summary": "test",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "uuid",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseDto"
                        }
                    }
                }
            }
        },
        "/delete-main-menu": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "delete-main-menu",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Main Menu Service"
                ],
                "summary": "delete-main-menu",
                "parameters": [
                    {
                        "description": "Body data",
                        "name": "Data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.Menu_Load_dto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseDto"
                        }
                    }
                }
            }
        },
        "/delete-module": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "delete-module",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Module Service"
                ],
                "summary": "delete-module",
                "parameters": [
                    {
                        "description": "Body data",
                        "name": "Data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.Menu_Load_dto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseDto"
                        }
                    }
                }
            }
        },
        "/delete-sub-menu": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "delete-sub-menu",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sub Menu Service"
                ],
                "summary": "delete-sub-menu",
                "parameters": [
                    {
                        "description": "Body data",
                        "name": "Data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.Menu_Load_dto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseDto"
                        }
                    }
                }
            }
        },
        "/forgot-password": {
            "post": {
                "description": "forgot-password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Forgot Password Service"
                ],
                "summary": "forgot-password",
                "parameters": [
                    {
                        "description": "Body data",
                        "name": "Data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.Username_Swag_dto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseDto"
                        }
                    }
                }
            }
        },
        "/geninfo": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "geninfo",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Login Token Logout Service"
                ],
                "summary": "geninfo",
                "parameters": [
                    {
                        "description": "Body data",
                        "name": "Data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Comp_year_token_input_dto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseDto"
                        }
                    }
                }
            }
        },
        "/get-all-active-inactive-module": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "get-all-active-inactive-module",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json",
                    "application/json"
                ],
                "tags": [
                    "Menu \u0026 Module Load Service"
                ],
                "summary": "get-all-active-inactive-module",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseDto"
                        }
                    }
                }
            }
        },
        "/get-all-app-user": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "get-all-app-user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Status Service"
                ],
                "summary": "get-all-app-user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseDto"
                        }
                    }
                }
            }
        },
        "/insert-main-menu": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "insert-main-menu",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Entry Service"
                ],
                "summary": "insert-main-menu",
                "parameters": [
                    {
                        "description": "Body data",
                        "name": "Data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.InsertMainMenu_dto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseDto"
                        }
                    }
                }
            }
        },
        "/insert-module": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "insert-module",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Entry Service"
                ],
                "summary": "insert-module",
                "parameters": [
                    {
                        "description": "Body data",
                        "name": "Data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.InsertModule_dto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseDto"
                        }
                    }
                }
            }
        },
        "/insert-sub-menu": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "insert-sub-menu",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Entry Service"
                ],
                "summary": "insert-sub-menu",
                "parameters": [
                    {
                        "description": "Body data",
                        "name": "Data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.InsertSubMenu_dto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseDto"
                        }
                    }
                }
            }
        },
        "/login-V2": {
            "post": {
                "description": "login",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Login Token Logout Service"
                ],
                "summary": "login",
                "parameters": [
                    {
                        "description": "Body data",
                        "name": "Data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.LoginV2_Swag_dto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseDto"
                        }
                    }
                }
            }
        },
        "/logout-V2": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "logout",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Login Token Logout Service"
                ],
                "summary": "logout",
                "parameters": [
                    {
                        "description": "Body data",
                        "name": "Data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.Username_Swag_dto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseDto"
                        }
                    }
                }
            }
        },
        "/main-menu-load": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "main-menu-load",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Entry Service"
                ],
                "summary": "main-menu-load",
                "parameters": [
                    {
                        "description": "Body data",
                        "name": "Data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.Menu_Load_dto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseDto"
                        }
                    }
                }
            }
        },
        "/main-sub-menu-load": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "main-sub-menu-load",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Menu \u0026 Module Load Service"
                ],
                "summary": "main-sub-menu-load",
                "parameters": [
                    {
                        "description": "Body data",
                        "name": "Data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.MenuSubMenuLoad_input_dto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseDto"
                        }
                    }
                }
            }
        },
        "/module-load": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "module-load",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json",
                    "application/json"
                ],
                "tags": [
                    "Entry Service"
                ],
                "summary": "module-load",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseDto"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "module-load",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Menu \u0026 Module Load Service"
                ],
                "summary": "module-load",
                "parameters": [
                    {
                        "description": "Body data",
                        "name": "Data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ModuleLoad_Swag_dto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseDto"
                        }
                    }
                }
            }
        },
        "/save-user-access": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "save-user-access",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Access Service"
                ],
                "summary": "save-user-access",
                "parameters": [
                    {
                        "description": "Body data",
                        "name": "Data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.SaveUserAccess_input_dto"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseDto"
                        }
                    }
                }
            }
        },
        "/select-module": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "module-load",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Menu \u0026 Module Load Service"
                ],
                "summary": "module-load",
                "parameters": [
                    {
                        "description": "Body data",
                        "name": "Data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.User_module"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseDto"
                        }
                    }
                }
            }
        },
        "/signup": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "signup",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SignUp Service"
                ],
                "summary": "signup",
                "parameters": [
                    {
                        "description": "Body data",
                        "name": "Data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.SignUp_Swag_dto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseDto"
                        }
                    }
                }
            }
        },
        "/sub-menu-load": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "sub-menu-load",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Entry Service"
                ],
                "summary": "sub-menu-load",
                "parameters": [
                    {
                        "description": "Body data",
                        "name": "Data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.SubMenuLoadINPUT_dto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseDto"
                        }
                    }
                }
            }
        },
        "/test": {
            "get": {
                "description": "test2",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json",
                    "application/json"
                ],
                "tags": [
                    "Test Service"
                ],
                "summary": "test2",
                "deprecated": true,
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseDto"
                        }
                    }
                }
            }
        },
        "/test/{id}": {
            "get": {
                "description": "test",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Test Service"
                ],
                "summary": "test",
                "deprecated": true,
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseDto"
                        }
                    }
                }
            }
        },
        "/token-time-extend": {
            "post": {
                "description": "token-time-extend",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Login Token Logout Service"
                ],
                "summary": "token-time-extend",
                "parameters": [
                    {
                        "description": "Body data",
                        "name": "Data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.Username_Swag_dto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseDto"
                        }
                    }
                }
            }
        },
        "/update-main-menu": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "update-main-menu",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Main Menu Service"
                ],
                "summary": "update-main-menu",
                "parameters": [
                    {
                        "description": "Body data",
                        "name": "Data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateMainMenu_dto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseDto"
                        }
                    }
                }
            }
        },
        "/update-module": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "update-module",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Module Service"
                ],
                "summary": "update-module",
                "parameters": [
                    {
                        "description": "Body data",
                        "name": "Data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateModule_dto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseDto"
                        }
                    }
                }
            }
        },
        "/update-sub-menu": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "update-sub-menu",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sub Menu Service"
                ],
                "summary": "update-sub-menu",
                "parameters": [
                    {
                        "description": "Body data",
                        "name": "Data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateSubMenu_dto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseDto"
                        }
                    }
                }
            }
        },
        "/user-lock": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "user-lock",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Status Service"
                ],
                "summary": "user-lock",
                "parameters": [
                    {
                        "description": "Body data",
                        "name": "Data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.User_lock_dto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseDto"
                        }
                    }
                }
            }
        },
        "/valid-user-load": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "valid-user-load",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json",
                    "application/json"
                ],
                "tags": [
                    "Branch \u0026 Financial Year Service"
                ],
                "summary": "valid-user-load",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseDto"
                        }
                    }
                }
            }
        },
        "/valid-user-select": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "valid-user-select",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Access Service"
                ],
                "summary": "valid-user-select",
                "parameters": [
                    {
                        "description": "Body data",
                        "name": "Data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ID_Swag_dto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseDto"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.BranchLoad": {
            "type": "object",
            "properties": {
                "comp_select_flag": {
                    "type": "boolean"
                },
                "compcode": {
                    "type": "integer"
                },
                "compname": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "dto.BranchSelect_dto": {
            "type": "object",
            "properties": {
                "compcode": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "dto.BranchYearSubmit_dto": {
            "type": "object",
            "properties": {
                "branch": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.BranchLoad"
                    }
                },
                "year": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.FinancialYearLoad"
                    }
                }
            }
        },
        "dto.Comp_year_token_input_dto": {
            "type": "object",
            "properties": {
                "compcode": {
                    "type": "integer"
                },
                "yearcode": {
                    "type": "integer"
                }
            }
        },
        "dto.Confirm_Swag_dto": {
            "type": "object",
            "properties": {
                "hash_password": {
                    "type": "string"
                },
                "otp_hash": {
                    "type": "string"
                }
            }
        },
        "dto.FinancialYearLoad": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                },
                "year_select_flag": {
                    "type": "boolean"
                },
                "yearcode": {
                    "type": "integer"
                }
            }
        },
        "dto.ID_Swag_dto": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                }
            }
        },
        "dto.InsertMainMenu_dto": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "order_id": {
                    "type": "integer"
                },
                "top_parent_id": {
                    "type": "integer"
                }
            }
        },
        "dto.InsertModule_dto": {
            "type": "object",
            "properties": {
                "module_icon_url": {
                    "type": "string"
                },
                "module_ui_url": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "order_id": {
                    "type": "integer"
                }
            }
        },
        "dto.InsertSubMenu_dto": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "order_id": {
                    "type": "integer"
                },
                "parent_id": {
                    "type": "integer"
                },
                "sub_menu_nav_url": {
                    "type": "string"
                },
                "top_parent_id": {
                    "type": "integer"
                }
            }
        },
        "dto.LoginV2_Swag_dto": {
            "type": "object",
            "properties": {
                "hash_password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "dto.MenuSubMenuLoad_input_dto": {
            "type": "object",
            "properties": {
                "compcode": {
                    "type": "integer"
                },
                "module_id": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "dto.Menu_Load_dto": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                }
            }
        },
        "dto.ModuleAccessFlag_dto": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "module_active": {
                    "type": "boolean"
                }
            }
        },
        "dto.ModuleLoad_Swag_dto": {
            "type": "object",
            "properties": {
                "compcode": {
                    "type": "integer"
                },
                "contactno": {
                    "type": "string"
                },
                "location": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                },
                "yearcode": {
                    "type": "integer"
                }
            }
        },
        "dto.Modules": {
            "type": "object",
            "properties": {
                "mainmenus": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "main_menu_id": {
                                "type": "integer"
                            },
                            "main_menu_name": {
                                "type": "string"
                            },
                            "submenus": {
                                "type": "array",
                                "items": {
                                    "type": "object",
                                    "properties": {
                                        "select_flag": {
                                            "type": "boolean"
                                        },
                                        "sub_menu_id": {
                                            "type": "integer"
                                        },
                                        "sub_menu_name": {
                                            "type": "string"
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                "module_id": {
                    "type": "integer"
                },
                "module_name": {
                    "type": "string"
                }
            }
        },
        "dto.ResponseDto": {
            "type": "object",
            "properties": {
                "geninfo": {},
                "isSuccess": {
                    "type": "boolean"
                },
                "message": {
                    "type": "string"
                },
                "payload": {},
                "statusCode": {
                    "type": "integer"
                }
            }
        },
        "dto.SaveUserAccess_input_dto": {
            "type": "object",
            "properties": {
                "compcode": {
                    "type": "integer"
                },
                "modules": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.Modules"
                    }
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "dto.SignUp_Swag_dto": {
            "type": "object",
            "properties": {
                "fullname": {
                    "type": "string"
                },
                "phoneno": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "dto.SubMenuLoadINPUT_dto": {
            "type": "object",
            "properties": {
                "parent_id": {
                    "type": "integer"
                },
                "top_parent_id": {
                    "type": "integer"
                }
            }
        },
        "dto.UpdateMainMenu_dto": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "order_id": {
                    "type": "integer"
                },
                "top_parent_id": {
                    "type": "integer"
                }
            }
        },
        "dto.UpdateModule_dto": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "module_icon_url": {
                    "type": "string"
                },
                "module_ui_url": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "order_id": {
                    "type": "integer"
                }
            }
        },
        "dto.UpdateSubMenu_dto": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "order_id": {
                    "type": "integer"
                },
                "parent_id": {
                    "type": "integer"
                },
                "sub_menu_nav_url": {
                    "type": "string"
                },
                "top_parent_id": {
                    "type": "integer"
                }
            }
        },
        "dto.User_lock_dto": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "user_lock": {
                    "type": "boolean"
                }
            }
        },
        "dto.Username_Swag_dto": {
            "type": "object",
            "properties": {
                "username": {
                    "type": "string"
                }
            }
        },
        "model.Comp_year_token_input_dto": {
            "type": "object",
            "properties": {
                "geninfo": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "model.User_module": {
            "type": "object",
            "properties": {
                "module_id": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    },
    "externalDocs": {
        "description": "OpenAPI",
        "url": "https://swagger.io/resources/open-api/"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.0",
	Host:             "118.67.213.45:7021",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "SITL Common API",
	Description:      "An API to perform `SITL Common API` operations. You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
